# Generated by Django 5.2.5 on 2025-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "job_id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("job_position", models.CharField(max_length=255)),
                ("job_link", models.URLField(max_length=500)),
                ("company_name", models.CharField(max_length=255)),
                ("company_profile", models.URLField(max_length=500)),
                ("job_location", models.CharField(max_length=255)),
                ("job_posting_date", models.DateField()),
                (
                    "company_logo_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Job Listing",
                "verbose_name_plural": "Job Listings",
                "ordering": ["-job_posting_date", "company_name"],
            },
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="location",
        ),
        migrations.RemoveField(
            model_name="accessibilitymap",
            name="location",
        ),
        migrations.DeleteModel(
            name="HealthcareFacility",
        ),
        migrations.DeleteModel(
            name="JobPosting",
        ),
        migrations.DeleteModel(
            name="AccessibilityLocation",
        ),
        migrations.DeleteModel(
            name="AccessibilityMap",
        ),
    ]

