# Generated by Django 5.2.5 on 2025-09-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcarefacility",
            name="hours",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthcarefacility",
            name="open_state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="healthcarefacility",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthcarefacility",
            name="reviews_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="company_logo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="company_profile",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="job_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="job_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="location_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="source",
            field=models.CharField(default="local", max_length=50),
        ),
        migrations.AlterField(
            model_name="accessibilitylocation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthcarefacility",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="healthcarefacility",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthcarefacility",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="theapp.accessibilitylocation",
            ),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="posted_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobposting",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
