# Generated by Django 5.2.5 on 2025-09-04 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theapp", "0003_load_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPSCoordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "verbose_name": "GPS Coordinates",
                "verbose_name_plural": "GPS Coordinates",
            },
        ),
        migrations.CreateModel(
            name="OperatingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monday", models.CharField(blank=True, max_length=50, null=True)),
                ("tuesday", models.CharField(blank=True, max_length=50, null=True)),
                ("wednesday", models.CharField(blank=True, max_length=50, null=True)),
                ("thursday", models.CharField(blank=True, max_length=50, null=True)),
                ("friday", models.CharField(blank=True, max_length=50, null=True)),
                ("saturday", models.CharField(blank=True, max_length=50, null=True)),
                ("sunday", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Operating Hours",
                "verbose_name_plural": "Operating Hours",
            },
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("place_id", models.CharField(max_length=255, unique=True)),
                ("data_id", models.CharField(blank=True, max_length=255, null=True)),
                ("data_cid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "reviews_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("photos_link", models.URLField(blank=True, max_length=500, null=True)),
                ("posts_link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "provider_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviews", models.IntegerField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("open_state", models.CharField(blank=True, max_length=100, null=True)),
                ("hours", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.URLField(blank=True, max_length=500, null=True)),
                ("thumbnail", models.URLField(blank=True, max_length=500, null=True)),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "google_maps_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("unclaimed_business", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gps_coordinates",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_result",
                        to="theapp.gpscoordinates",
                    ),
                ),
                (
                    "operating_hours",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_result",
                        to="theapp.operatinghours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Result",
                "verbose_name_plural": "Search Results",
                "ordering": ["-rating", "-reviews"],
            },
        ),
        migrations.CreateModel(
            name="SearchResultType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=255)),
                (
                    "search_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="theapp.searchresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Result Type",
                "verbose_name_plural": "Search Result Types",
                "unique_together": {("search_result", "type_name")},
            },
        ),
    ]
